// players
export const FETCH_PLAYERS_SUCCESS = 'FETCH_PLAYERS_SUCCESS';
export const MODIFY_PLAYER_SUCCESS = 'MODIFY_PLAYER_SUCCESS';
export const CLEAR_ALL_PLAYERS = 'CLEAR_ALL_PLAYERS';

// playerTable
export const UPDATE_PLAYER_TABLE = 'UPDATE_PLAYER_TABLE';

// playerInfoDialog
export const OPEN_PLAYER_INFO_DIALOG = 'OPEN_PLAYER_INFO_DIALOG';
export const CLOSE_PLAYER_INFO_DIALOG = 'CLOSE_PLAYER_INFO_DIALOG';

// deletePlayerDialog
export const OPEN_DELETE_PLAYER_DIALOG = 'OPEN_DELETE_PLAYER_DIALOG';
export const CLOSE_DELETE_PLAYER_DIALOG = 'CLOSE_DELETE_PLAYER_DIALOG';

// alerts
export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';
